version: "2"
services:
    nginx:
      image: portfolio-nginx:1.0
      build: ./nginx
      container_name: portfolio-nginx
      volumes:
        - ./nginx:/etc/nginx/conf.d
      ports:
        - "80:80"
        - "443:443"
      networks:
        - backbone
    portfolio:
      container_name: portfolio
      image: portfolio:1.0
      build: ./my-portfolio
      networks:
        - backbone
      expose: 
        - 80
    battle-ship:
      container_name: battle-ship
      image: battle-ship:1.0
      build: ./battle_ship_frontend
      networks:
        - backbone
      expose: 
        - 80
    battle-ship-backend:
      container_name: battle-ship-backend
      image: battle-ship-backend:1.0
      build: ./battle_ship_backend
      networks:
        - backbone
      expose: 
        - 5000
networks:
  backbone:
    driver: bridge