version: "2"
services:
    nginx:
      image: nginx:alpine
      # build: ./nginx
      container_name: nginx
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/ssl
      ports:
        - "80:80"
        - "443:443"
      networks:
        - backbone
    portfolio:
      container_name: my-portfolio
      image: yoavdocker89/my-portfolio:latest
      build: ./my-portfolio
      networks:
        - backbone
      expose: 
        - 80
    battle-ship-frontend:
      container_name: battle-ship-frontend
      image: yoavdocker89/battle-ship-frontend:latest
      build: ./battle_ship_frontend
      networks:
        - backbone
      expose: 
        - 80
    battle-ship-backend:
      container_name: battle-ship-backend
      image: yoavdocker89/battle-ship-backend:latest
      build: ./battle_ship_backend
      networks:
        - backbone
      ports: 
        - "5000:5000"
networks:
  backbone:
    driver: bridge