apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: portfolio
  name: portfolio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portfolio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/portfolio-project-backbone: "true"
        io.kompose.service: portfolio
    spec:
      containers:
        - image: yoavdocker89/my-portfolio:latest
          name: my-portfolio
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
